from __future__ import annotations
import pathlib, tempfile, unittest
from repo_context.cache import CACHE_VERSION
from repo_context.parsers import summarize_source
from repo_context.scanner import build_index, changed_view, dependency_view, module_map, project_map, query_view
from repo_context.cli import inspect_file, _symbol_with_ledger
from repo_context.context_planner import build_context
from repo_context.indexer import build_persistent, ensure_index, index_status
from repo_context.router import route_task
from repo_context.admission import evaluate_read
ROOT=pathlib.Path(__file__).resolve().parents[1]
class RepoContextTests(unittest.TestCase):
    def test_map_outputs_top_k_not_all_files(self):
        idx=build_index(ROOT/'examples/sample-project',use_cache=False); r=project_map(idx,top_k=2); self.assertEqual(len(r['important_files']),2); self.assertGreater(idx['stats']['files_scanned'],2); self.assertNotIn('files',r)
    def test_dependency_graph_relative_js(self):
        idx=build_index(ROOT/'examples/sample-project',use_cache=False); self.assertIn('src/services/order.js',dependency_view(idx,'src/routes/order.js')['imports']); self.assertIn('src/services/payment.js',dependency_view(idx,'src/services/order.js')['imports'])
    def test_query_ranking_prefers_payment(self):
        idx=build_index(ROOT/'examples/sample-project',use_cache=False); paths=[f['path'] for f in project_map(idx,top_k=3,query='payment charge checkout')['important_files']]; self.assertIn('src/services/payment.js',paths[:3])
    def test_python_ast(self):
        s=summarize_source('demo.py','import os\nclass Demo:\n    async def run(self,value):\n        return value\n'); self.assertEqual(s['parser'],'python-ast'); self.assertIn('Demo',s['classes']); self.assertTrue(any(x.startswith('run(') for x in s['functions']))
    def test_js_arrow(self): self.assertTrue(any(x.startswith('charge(') for x in summarize_source('demo.ts','export const charge = async (amount: number) => amount;\n')['functions']))
    def test_secret_paths_skipped(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main(): pass\n'); (r/'.env').write_text('SECRET=x'); (r/'credentials.json').write_text('{}'); idx=build_index(r,use_cache=False,include_hidden=True); paths={f['path'] for f in idx['files']}; self.assertIn('main.py',paths); self.assertNotIn('.env',paths); self.assertNotIn('credentials.json',paths)
    def test_generated_skipped(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main(): pass\n'); (r/'client.py').write_text('# Code generated by tool. DO NOT EDIT.\ndef api(): pass\n'); self.assertNotIn('client.py',{f['path'] for f in build_index(r,use_cache=False)['files']})
    def test_workspace_detection(self): self.assertIn('packages/shared',{w['path'] for w in build_index(ROOT/'examples/sample-project',use_cache=False)['workspaces']})
    def test_module_map(self): self.assertTrue(all(x['path'].startswith('src/services/') for x in module_map(build_index(ROOT/'examples/sample-project',use_cache=False),'src/services',top_k=10)['important_files']))
    def test_cache_hits(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main(): pass\n'); self.assertEqual(build_index(r,use_cache=True)['stats'].get('cache_hits',0),0); self.assertGreaterEqual(build_index(r,use_cache=True)['stats'].get('cache_hits',0),1)
    def test_persistent_index(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main():\n return 1\n'); b=build_persistent(r,use_cache=True); self.assertTrue(index_status(r)['indexed']); self.assertEqual(b['mode'],'built')
    def test_no_sync_requires_index(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main(): pass\n');
            with self.assertRaises(ValueError): ensure_index(r,sync=False,use_cache=True)
    def test_runtime_state_single_dir(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'main.py').write_text('def main(): pass\n'); build_persistent(r,use_cache=True); self.assertTrue((r/'.repo-context/cache'/f'summaries-v{CACHE_VERSION}.json').is_file()); self.assertFalse((r/'.repo-context-cache').exists())
    def test_query_view_distinct(self): self.assertIn('matches',query_view(build_index(ROOT/'examples/sample-project',use_cache=False),'payment',top_k=3))
    def test_router_debug(self): self.assertEqual(route_task('payment fails with an exception during checkout')['task_type'],'debug')
    def test_context_budget_symbols(self):
        idx=build_index(ROOT/'examples/sample-project',use_cache=False); r=build_context(idx,'payment checkout order',budget=1800,session='test-budget'); self.assertLessEqual(r['budget']['estimated_used_tokens'],1800); self.assertTrue(r['files']); self.assertTrue(any(s['name'] in {'charge','checkout','createOrder'} for s in r['symbols']))
    def test_symbol_session_dedup(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'service.py').write_text('def charge(amount):\n return amount\n'); first=_symbol_with_ledger(r,'service.py','charge','s1',100000); second=_symbol_with_ledger(r,'service.py','charge','s1',100000); self.assertEqual(first['content_mode'],'full-symbol'); self.assertEqual(second['content_mode'],'omitted-unchanged')
    def test_read_admission(self):
        with tempfile.TemporaryDirectory() as td:
            r=pathlib.Path(td); (r/'auth.py').write_text('def login():\n return True\n'+'\n'.join(f'# line {i}' for i in range(500))); d=evaluate_read(build_index(r,use_cache=False),'auth.py','login authentication failure',requested='full'); self.assertFalse(d['allow']); self.assertEqual(d['decision'],'prefer-symbol')
if __name__=='__main__': unittest.main()
