from __future__ import annotations

import hashlib
import json
import pathlib
import re
from typing import Iterable, Any

SOURCE_EXTENSIONS = {
    ".py": "Python",
    ".js": "JavaScript", ".mjs": "JavaScript", ".cjs": "JavaScript",
    ".ts": "TypeScript", ".tsx": "TypeScript", ".jsx": "JavaScript",
    ".cs": "C#", ".rs": "Rust", ".go": "Go",
    ".java": "Java", ".kt": "Kotlin", ".kts": "Kotlin",
    ".rb": "Ruby", ".php": "PHP", ".swift": "Swift",
    ".c": "C", ".h": "C/C++", ".cc": "C/C++", ".cpp": "C/C++", ".hpp": "C/C++",
    ".vue": "Vue", ".svelte": "Svelte", ".sql": "SQL",
    ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell", ".ps1": "PowerShell",
}
TEXT_CONFIG_EXTS = {".json", ".toml", ".yaml", ".yml", ".xml", ".ini", ".cfg", ".md"}
MANIFEST_NAMES = {"package.json", "pyproject.toml", "requirements.txt", "Pipfile", "poetry.lock", "Cargo.toml", "go.mod", "pom.xml", "build.gradle", "build.gradle.kts", "Gemfile", "composer.json", "Package.swift", "Dockerfile", "docker-compose.yml", "docker-compose.yaml", "pnpm-workspace.yaml", "turbo.json", "nx.json", "lerna.json"}
ENTRY_NAMES = {"main.py", "app.py", "manage.py", "__main__.py", "index.js", "index.ts", "index.tsx", "main.js", "main.ts", "main.tsx", "server.js", "server.ts", "Program.cs", "Main.java", "main.rs", "lib.rs", "main.go", "App.tsx", "App.jsx"}
DEFAULT_IGNORE_DIRS = {".git", ".hg", ".svn", ".idea", ".vscode", ".next", ".nuxt", ".turbo", ".cache", ".pytest_cache", ".mypy_cache", ".ruff_cache", "__pycache__", "node_modules", "vendor", "dist", "build", "target", "bin", "obj", "coverage", ".coverage", ".venv", "venv", "env", ".tox", ".gradle", ".repo-context-cache", ".repo-context"}
SECRET_NAME_PATTERNS = [re.compile(r"(^|/)\.env(?:\.|$)", re.I), re.compile(r"(^|/)(?:secrets?|credentials?)(?:\.|/|$)", re.I), re.compile(r"\.(?:pem|key|p12|pfx|jks)$", re.I), re.compile(r"(?:id_rsa|id_ed25519)$", re.I)]
GENERATED_PATH_PATTERNS = [re.compile(r"(?:^|/)(?:generated|gen|dist|build|coverage|vendor)(?:/|$)", re.I), re.compile(r"(?:\.min\.(?:js|css)|\.g\.dart|\.designer\.cs)$", re.I)]

def estimate_tokens_from_bytes(size: int) -> int:
    return max(1, (size + 3) // 4) if size else 0

def compact_signature(value: str, limit: int = 180) -> str:
    s = re.sub(r"\s+", " ", value.strip()); return s[:limit] + ("…" if len(s) > limit else "")

def uniq(values: Iterable[str], cap: int = 50) -> list[str]:
    seen=set(); out=[]
    for value in values:
        value=value.strip()
        if value and value not in seen: seen.add(value); out.append(value)
        if len(out)>=cap: break
    return out

def is_manifest(path: pathlib.Path) -> bool:
    return path.name in MANIFEST_NAMES or path.suffix.lower() in {".csproj", ".sln"}

def is_secret_path(rel: str) -> bool: return any(p.search(rel) for p in SECRET_NAME_PATTERNS)
def is_generated_path(rel: str) -> bool: return any(p.search(rel) for p in GENERATED_PATH_PATTERNS)
def looks_generated(text: str) -> bool:
    head="\n".join(text.splitlines()[:8]).lower(); return any(m in head for m in ("code generated", "auto-generated", "autogenerated", "do not edit", "generated by"))
def safe_read_text(path: pathlib.Path, max_bytes: int) -> tuple[str | None, int, str | None]:
    try:
        if path.is_symlink(): return None,0,"symlink"
        size=path.stat().st_size
        if size>max_bytes:return None,size,"large"
        data=path.read_bytes()
        if b"\x00" in data[:4096]:return None,size,"binary"
        return data.decode("utf-8",errors="replace"),size,None
    except (OSError,PermissionError): return None,0,"unreadable"
def file_cache_key(path: pathlib.Path) -> str:
    st=path.stat(); return hashlib.sha256(f"{path.resolve()}|{st.st_mtime_ns}|{st.st_size}".encode()).hexdigest()
def json_bytes(value: Any) -> int:
    return len(json.dumps(value,ensure_ascii=False,separators=(",",":")).encode("utf-8"))
